name: Probar Runner de ARC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Usa tus etiquetas personalizadas para el Runner de Kubernetes
    runs-on: arc-runner-set

    steps:
      - name: Verificar el runner
        run: |
          echo "¡Hola desde mi runner en Kubernetes (ARC)!"
          echo "Este trabajo corre en el runner: $RUNNER_NAME"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validar AWS CLI e Identidad
        run: |
          echo "Verificando instalación de AWS CLI..."
          aws --version
          
          echo "Verificando permisos de IAM (IRSA)..."
          # Este comando es vital para confirmar que el runner puede hablar con AWS
          aws --version
          zip -v

      - name: Ejecutar un build (ejemplo)
        run: |
          echo "Simulando un build..."
          sleep 5
          echo "Build completado."
